language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"

jobs:
    allow_failures:
    - python: "3.9-dev"

install: pip install tox-travis

script: tox

notifications:
  email: false
